# Generated by Django 3.2.6 on 2021-08-12 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do Aluno', max_length=100)),
                ('cpf', models.CharField(help_text='CPF do Aluno', max_length=12)),
            ],
        ),
    ]
